# This file was generated by GoReleaser. DO NOT EDIT.
cask "unreal-agent" do
  binary "unreal-agent-tui", target: "unreal-agent"
  binary "unreal-agent-tui", target: "uat"
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "."], chdir: "."
    end
  end

  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "026c47ff4b6ed4089a884d92c58e35b371894e57e6fdfb5450620d8f743aca81"
      url "https://github.com/unreallabsai/unreal-agent/releases/download/v#{version}/unreal-agent_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e833196ca7c1cafc49bd9279c90dde4b0faa985b1f456bfdf54609770edfd57"
      url "https://github.com/unreallabsai/unreal-agent/releases/download/v#{version}/unreal-agent_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b01b096d0543277b2d58d8928da7a7df32b7dcb546a86335de2d04c81eea507b"
      url "https://github.com/unreallabsai/unreal-agent/releases/download/v#{version}/unreal-agent_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd6e15236cc6f126ea3ddf2fc85c4be05bc5e8e4967977a89720bf95e22b304b"
      url "https://github.com/unreallabsai/unreal-agent/releases/download/v#{version}/unreal-agent_#{version}_linux_amd64.tar.gz"
    end
  end

  name "unreal-agent"
  desc "Unreal Agent terminal interface and headless runner"
  homepage "https://github.com/unreallabsai/unreal-agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unreal-agent-runner"
  binary "unreal-agent-tui"

  # No zap stanza required
end
